channels:
  - conda-forge
dependencies:
  - python >=3.11
  - numpy >=1.25.2
  - pip >=23.3.1
  - pyramids >=0.5.4
  - geopandas >=0.14.1
  - pandas >=2.1.0
  - matplotlib >=3.7.2
  - cleopatra >=0.4.0
  - serapeum_utils >=0.2.0
  - statista >=0.5.0
  - statsmodels >=0.14.1
  - loguru >=0.7.2
  - pathlib >=1.0.1
  - pytest >=7.4.3
  - pytest-cov >=4.1.0
